version: 2
jobs:
  build:
    docker:
      - image: turbinelabs/build-common:0.10.0.0
        cmd: ["/bin/bash"]

    working_directory: "/go/src/github.com/turbinelabs/cli"

    environment:
      - PROJECT: github.com/turbinelabs/cli
      - TEST_RUNNER_OUTPUT: /tmp/test-results/testrunner
      - TBN_CI_BUILD: 1
      - TBN_COVERAGE_UPLOAD: 1

    steps:
      - checkout

      - run: env | sort

      - run:
          name: install deps
          command: go get $PROJECT/...

      - run:
          name: install testrunner
          command: |
            go get github.com/turbinelabs/test/testrunner
            go install github.com/turbinelabs/test/testrunner

      - run:
          name: run tests
          command: bash code_coverage.sh $(go list $PROJECT/... | grep -v /vendor/)

      - store_test_results:
          path: /tmp/test-results
