// Automatically generated by MockGen. DO NOT EDIT!
// Source: version.go

package app

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Version interface
type MockVersion struct {
	ctrl     *gomock.Controller
	recorder *_MockVersionRecorder
}

// Recorder for MockVersion (not exported)
type _MockVersionRecorder struct {
	mock *MockVersion
}

func NewMockVersion(ctrl *gomock.Controller) *MockVersion {
	mock := &MockVersion{ctrl: ctrl}
	mock.recorder = &_MockVersionRecorder{mock}
	return mock
}

func (_m *MockVersion) EXPECT() *_MockVersionRecorder {
	return _m.recorder
}

func (_m *MockVersion) Print() {
	_m.ctrl.Call(_m, "Print")
}

func (_mr *_MockVersionRecorder) Print() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Print")
}
